//Webseite fuer Schueler mit Basic Informationen
// @author Katrin Rabow
//
= Willkommen bei AnimAl

Schön, dass du auf unserer Seite gelandet bist! Wir haben ein kleines Programm entwickelt, mit dem du ganz einfach sehen kannst, wie verschiedene Such- und Sortieralgorithmen aus der Informatik funktionieren.

Wenn du das Programm direkt herunterladen willst, dann <<AnimalDownloaden,klick bitte hier>>.

Falls du noch weitere Informationen lesen willst, dann schau einfach ins Menü.

Viel Spaß!

[[AnimalDownloaden]]
= ANIMAL downloaden

Hier findest du immer die neueste Version von ANIMAL. Du kannst sie direkt herunterladen und starten oder dir erst die Dokumentation dazu durchlesen.

= Installation

Um das Programm auf deinem PC ausführen zu können, brauchst du eine Java-Version 7 oder höher. Hier findest du eine Anleitung, wie du prüfen kannst, ob du das schon installiert hast oder du kannst dir Java über diesen Link installieren, falls es auf deinem PC noch nicht vorhanden ist.

Nun lade dir bitte die aktuelle Version von ANIMAL herunter, indem du die Datei mit der Endung .jar auf deinen PC speicherst (d.h. du klickst die Datei mit der rechten Maustaste an und wählst "speichern" oder "speichern unter", wenn du sie in einem bestimmten Ordner auf deinem PC speichern willst).

Am besten lädst du dir gleich noch das ZIP-File herunter, das ziemlich viele Animationen beinhaltet. Damit kannst du dann nach der Installation direkt starten, dir verschiedene Algorithmen anzuschauen. Den Download gibt es auf deutsch oder englisch - in dieser Sprache sind dann später die Texte in den Animationen, also achte darauf, die richtige Sprache zu wählen.
Nun musst du das ZIP-File nur noch entpacken (mit der rechten Maustaste anklicken bringt meistens eine Funktion "entpacken" oder "unzip"), am besten in einen eigenen Ordner auf deinem PC.

Um endlich loslegen zu können, suchst du jetzt die JAR-Datei, die du als erstes gespeichert hast und startest durch Doppelklick auf diese Datei das Programm. Es erscheint ein kleines Fenster auf dem Bildschirm, wo du siehst, dass dein PC arbeitet und danach öffnet sich das Hauptfenster des Programms ANIMAL.

Wie es weitergeht, findest du auf der Seite Schnellstart.

= Schnellstart

Falls du das Programm noch nicht installiert hast, // TODO

Du startest das Programm immer durch Doppelklick auf die animal-.jar -Datei, die du am Anfang gespeichert hast. Es erscheint ein kleines Fenster auf dem Bildschirm, wo du siehst, dass dein PC arbeitet und danach öffnet sich das Hauptfenster des Programms ANIMAL.

Wenn du eine bestehende Animation anschauen willst, klicke bitte auf "Open" und suche den Ordner, in dem du vorher die Dateien aus dem ZIP-File abgelegt hast. Hier klickst du an, welche Animation du sehen willst, bestätigst mit "OK" und siehst nun im Animationsfenster, wie der gewählte Algorithmus funktioniert.

= Java Überprüfung

= Datenschutz

