= Interne Dokumentation

== AsciiDoc

Damit die Dokumentation mit dem gesamten Code in der Versionsverwaltung eingecheckt werden kann, wird für die Dokumentation Ascii Doc verwendet (https://asciidoctor.org/). +
Dazu muss in IntellJ das AsciiDoc-Plugin installiert werden, dann kann ein file *.adoc angelegt werden, das jeweils direkt als PDF oder HTML ausgegeben werden kann. +
AsciiDoc hat eine recht einfache Syntax, so dass ohne großen Aufwand ein Dokument erzeugt werden kann: +
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/ +
Damit es später keine Probleme bei der Versionsverwaltung der AsciiDocs gibt, sollte in jeder Zeile jeweils nur ein Satz stehen.

== Webseite bauen

Der Nutzer soll über eine Web-Seite über AnimAl informiert werden, dort die Programmdateien und Anleitungen finden.
Der HTML-Code für diese Seite kann direkt aus AsciiDoc erzeugt werden, allerdings ist dann noch keine Seite gebaut.
Eine sehr einfache Seite lässt sich aus dem AsciiDoc mit JBake (https://jbake.org/) erzeugen, was hier vorerst für die abgespeckte Webseite für Schüler erfolgt. +
Verschiedene Templates zum Bauen der Navigation / Header usw. sind bereits vorhanden und müssen nur angepasst werden.
Da in der zugrunde gelegten Literatur zum Zusammenspiel von AsciiDoc und JBake (https://www.informatik-aktuell.de/entwicklung/methoden/docs-as-code-alles-unter-einem-dach.html) Gradle als Build Tool genommen wurde, haben wir es auch hier verwendet.

== Einfache Funktionen von JBAke

Der jeweilige Content einer Seite wird als <<AsciiDoc>> Datei im Ordner content geschrieben.
Jede Datei muss am Anfang mindestens die Angaben haben, um welchen Typ von Inhalt es sich handelt (z.B. :jbake-type:page) und wie der Status (z.B. :jbake-status:published)ist.
Weitere Attribute wie Datum oder Tags können optional hinzugefügt werden.
Durch Eingabe von jbake -b werden daraus die html-Seiten im Ordner output erzeugt.
Mit jbake -s wird direkt im Browser das Ergebnis daraus angezeigt.
Der Ordner templates enthält verschiedene Templates, die mit dem JBake-Projekt angelegt wurden.
Im menu.ftl kann die Navigationsleiste der Webseite angepasst werden.

Ausführlichere Infos finden sich auf https://jbake.org/docs/2.6.4/#quickstart_guide
