= Konzept für die weitere Entwicklung von ANIMAL

== Installer

Zur Zeit müssen verschiedene Dateien heruntergeladen und gespeichert werden.
Die Ausführung des Tools erfolgt über die .jar-Datei.
Für die Zukunft wäre insbesondere im Hinblick auf die Benutzung durch SchülerInnen, die noch nicht so versiert im Umgang mit ihrem Rechner sind, ein Installer wünschenswert.
Von vielen anderen Anwendungen ist bekannt, nur auf einen "Download"-Button klicken zu müssen, womit sich das Tool installiert.
Die spätere Ausführung des Tools könnte über den Programmaufruf erfolgen.

== Qualitätssicherung Webseite

Für die Webseite kann eine Überprüfung aller Links eingebaut werden.
Damit kann in Zukunft bei jeder Änderung vor Veröffentlichung der neuen Seite geprüft werden, ob alle Links gültig sind.
Andernfalls wird die Seite gar nicht erst veröffentlicht.

== Eigener Bereich SchülerInnen in ANIMAL

Für SchülerInnen relevante Algorithmen werden in einem separaten Bereich vorgestellt, damit die Zielgruppe hier gezielt nachschauen kann.
Gleichzeitig sollen alle Benutzer Zugriff auf sämtliche Inhalte haben.

== Beschreibung der Algorithmen für SchülerInnen

Insbesondere für SchülerInnen, aber auch für wenig erfahrene Nutzer sollten Algorithmen so beschrieben werden, dass sie auch dann verständlich sind, wenn sie vorher völlig unbekannt waren.
Dafür müssen alle Texte geprüft und ggf. überarbeitet werden.

== Mobile App

Langfristig sollte ein Ziel sein, ANIMAL als mobile app anzubieten, da SchülerInnnen vorwiegend auf mobilen Geräten unterwegs sind und in der Regel eher Apps als Browser-Anwendungen benutzen.

== User Guide englische Version

Die englische Version des User Guide muss überarbeitet werden (ist von 2000!).
Teilweise sind sehr alte Systemangaben vorhanden, teilweise sind Links nicht mehr gültig.
Zusätzlich muss auf inhaltliche Änderungen geprüft werden.
Ziel sollte sein, den englischen User-Guide ebenfalls als AsciiDoc zu schreiben, um ihn leicht anpassen zu können bei neuen Versionen.
